ARG BUILD_TAG
FROM ryugu-psie-docker-dev-local.jfrog.io/equinix/virtlet-build-base:${BUILD_TAG}
MAINTAINER Brandon Feng <bfeng@equinix.com>

LABEL virtlet.image="build"

RUN mkdir -p /go/src/github.com/Equinix/virtlet
WORKDIR /go/src/github.com/Equinix/virtlet

COPY image_skel /.
# this conf file runs the emulator as root which is ok for
# testing purposes
COPY qemu-build.conf /etc/libvirt/qemu.conf
