network-config:
  links:
  - ethernet_mac_address: "00:11:22:33:44:55"
    id: cni0
    mtu: 1500
    type: phy
  - ethernet_mac_address: 00:11:22:33:ab:cd
    id: cni1
    mtu: 1500
    type: phy
  networks:
  - id: net-0
    link: cni0
    network_id: net-0
    type: ipv4_dhcp
  - id: net-1
    link: cni1
    network_id: net-1
    type: ipv4_dhcp
  services:
  - address:
    - 1.2.3.4
    search:
    - some
    - search
    type: nameserver
